### PR TITLE
add https and switch from nodesource to nvm

### PR DESCRIPTION
**Pull request by opadron**
This PR would add our new SSL cert and credentials to our deployment processes.  Due to the nature of the change, there is a high likelihood that a site outage will be necessary (though I'm secretly hoping that all my work on the deployment infrastructure is going to pay off and no one is going to notice any outage at all!).

I have outlined my proposed work plan for the update, below.  Please consider that things will go smoother if we can get osumo/osumo-project#5 reviewed and merged before executing on this plan.

### Proposed Work Plan

- [x] Update file-selector widget to include a link to the girder UI.
- [x] Manually update sumobot to this PR.
- [x] Add temporary commit that would allow testing the SSL connection on the staging environment.
- [x] Test this PR by running trial staging operations.
- [x] Correct any issues or defects discovered until a successful stage operation completes.
- [x] Assess the SSL connection on the staging environment to confirm correct operation of our new cert.
- [x] Revert temporary commit.
- [x] Manually update sumobot to this PR after all the new commits.
- [x] Test this PR by running trial staging operations, confirm that staging no longer serves over HTTPS.
- [x] **Announce a possible site outage for SSL.**
- [x] Test this PR by running trial deploy operations.
- [x] Correct any issues or defects discovered until a successful deploy operation completes.
- [x] Assess the SSL connection on the production environment to confirm correct operation of our new cert.
- [x] **Announce the end of the site outage for SSL.**
- [x] Remove old commented section for nodesource nodejs installation.
- [x] Clean up anything else lingering in this PR.
- [x] Merge this PR.
- [x] Automatically update sumobot to new master through slack.
- [x] Merge osumo/osumo-project#5
- [x] Stage osumo/osumo-project#5
- [x] Assess user login features on staging environment and confirm correct operation.
- [x] **Announce a possible site outage for user logins.**
- [x] Deploy osumo/osumo-project#5
- [x] Assess user login features on production environment and confirm correct operation.
- [x] **Announce the end of the site outage for user logins.**

### CODE REVIEW

**Comment by waxlamp** [comment]
Code seems to be ok (though I don't have much experience with deploying HTTPS). I like the use of `.j2` template files to hide the private keys.

Work plan seems ok as well. I don't understand all the details but overall it seems reasonable.

Can you tell me what nodesource/nvm are being used for? I haven't used either package before and they seem like they're meant for managing multiple deployments of NPM?

**Comment by opadron** [comment]
nvm and nodesource are two options for installing nodejs.

Nodesource refers to the APT repositories managed by the [company](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories/) of the same name.  These packages don't give us the level of control over the version of node used in production that I think is necessary.

[nvm (Node version manager)](https://github.com/creationix/nvm) is basically python virtual environments, but for nodejs.  I wanted to switch to it because we are already using it for testing on Travis, and I wanted to keep the gap between our development and production environments as narrow as practical.  It offers a simple mechanism to pin the version of nodejs that we use, so we can just say `nvm use ( v6 or v7 or master or hash or... )` in our service scripts and be on our way.

**Review by jeffbaumes — APPROVED** [review]

**Comment by opadron** [comment]
Work has begun on the update. No ETA.

**Comment by opadron** [comment]
Go-to-girder PR added osumo/osumo#35.

**Comment by opadron** [comment]
New update PR created. osumo/osumo-project#6
PR will incorporate osumo/osumo#35 once it is merged.
After this point, the first item in the work plan will be complete.

**Comment by opadron** [comment]
osumo/osumo#35 is pending review

**Comment by opadron** [comment]
osumo/osumo#35 merged
osumo/osumo-project#6 merged

File selector widget update complete.

**Comment by opadron** [comment]
sumobot updated to this latest PR

**Comment by opadron** [comment]
Temporary commit locally added.

**Comment by opadron** [comment]
Trial staging operations underway.

**Comment by opadron** [comment]
Trial Stage OP 1 Failed at playbook execution phase.

**Comment by opadron** [comment]
The issue was diagnosed.  The way sumobot was handling playbook variables made working with multi-line strings impossible.  I've switch to having the environments dumped into files sitting alongside the inventory.

Trial Stage OP 2 underway.

**Comment by opadron** [comment]
Trial Stage 2 failed at prep phase.  Issue is likely syntax errors in the playbooks.

**Comment by opadron** [comment]
Trial Stage 2 issue resolved.  Trial Stage 3 underway.

**Comment by opadron** [comment]
Trial Stage 3 failed at nodejs install step.  Issue is likely syntax errors in wget arguments.

**Comment by opadron** [comment]
Trial Stage 3 issue resolved.  Trial Stage 4 underway.

**Comment by opadron** [comment]
Trial Stage 4 timed out on the "wait for girder" step.

What I think is happening is that the SSL certificate is being (correctly) rejected because it is coming from a domain that is not "osumo.org".  If this is the case, then I will need to adjust the work plan so that I skip testing the SSL certificate until I try to deploy.

**Comment by opadron** [comment]
Turns out that Trial Stage 4's failure was unrelated to the SSL certificate.  Investigation ongoing.

**Comment by opadron** [comment]
It may be that Trial Stage 4's issue was just related to permissions.

**Comment by opadron** [comment]
I've determined that the issue with the Stage 4 attempt is due to a bug in NVM.  The issue has been resolved and Trial Stage 5 is underway.

**Comment by opadron** [comment]
Trial Stage 5 was completed successfully.  If you point your browser at the elastic ip for our testing environment ([52.86.100.86](http://52.86.100.86)), you should get the SSL error warning you that your connection may not be private.

I'm pretty sure you get the error only because the cert is not currently being used on osumo.org, but on the staging environment.  If you proceed anyway, enable developer tools on the page, and check under "security", you should find that the actual connection is encrypted and secured.  This result demonstrates that the cert works as intended and that our deployment processes should be able to handle the transition to production without much more issues.

With this work complete, I am going to push the local commits that got me to this point, and retire for the evening.  Execution on this plan will resume some time tomorrow afternoon, at which point I will make another announcement.

**Comment by opadron** [comment]
I am resuming the update, now.

**Comment by opadron** [comment]
Trial staging OP 6 completed successfully.  Removal of SSL certificate from staging environment confirmed.

At this moment, we have arrived at the first point in the process that may cause an outage to the production site.  ETA to successful SSL deployment: 30 minutes.

**Comment by opadron** [comment]
Deploy completed successfully.  SSL certificate installed and operational.  User account login features are live.  Because the tagged update also included osumo/osumo-project#5, there is no need for further updates, and therefor no more risk of possible outages.

The only tasks that remain are for any last-minute QA changes for the PR, itself.  I will hold off until Monday in case there is any feedback on this PR.  At that time, I will merge this and formally bring sumobot up-to-date.

**Comment by jeffbaumes** [comment]
🎉 🎈 

I see the🔒 now, and was able to make an account. Nice and secure.

**Comment by opadron** [comment]
@jeffbaumes great!  But, as we're learning from sysadmin, there are still a few outstanding issues that I will address in this PR before merging.

- [x] When I tried to use osumo.org, I was not able to run any jobs.  This issue needs to be resolved.
- [x] There are several issues with how we've set up our SSL configuration.  The fixes have already been identified and just need to be added to this PR.

**Comment by opadron** [comment]
It looks like the girder worker issue was related to the SSL problem.  Now, that I've temporarily fixed the SSL configuration, uploading results back to Girder is working properly.

So, we'll say for now that point # 1 is already done. :)

**Comment by opadron** [comment]
I'm gonna test out these fixes.

I'd still point out that there is a chance for an outage, but at this point, I'm pretty confident that no one is going to notice!



...famous last words...

**Comment by opadron** [comment]
Boy, that took a long time to find a pretty darn subtle bug.

Ok, here goes nothing!

**Comment by opadron** [comment]
Everything looks solid!
https://www.ssllabs.com/ssltest/analyze.html?d=osumo.org

Merging, now.

**Pull request merged**
